export const CUSTOMER_MODEL_KEYS = {
    USER_ID: 'userId',
    FIRST_NAME: 'firstName',
    LAST_NAME: 'lastName',
    EMAIL: 'email',
    DOB: 'dob',
    COUNTRY_CODE: 'countryCode',
    CONTACT_PREFIX: 'contactPrefix',
    CONTACT: 'contact',
    ADDRESS: 'address',
    COMPANY_NAME: 'companyName',
    COMPANY_LOGO: 'companyLogo',
    DESCRIPTION: 'description',
    WEBSITE: 'website',
    SOCIAL_MEDIA: 'socialMedia',
    LOCATION: 'location',
}
