export enum ORDER_STATUS {
    TECHNICAL = 1,
    SAMPLE = 2,
    PRODUCTION = 3,
    COMPLETED = 4,
    ARCHIVE = 5,
}

export enum SKU_ORDER_STATUS {
    QUOTATION = 1,
    DESIGN = 2,
    FABRIC_SOURCING = 3,
    ADMIN_TECHNICAL = 4,
    CUSTOMER_TECHNICAL = 5,
    ADMIN_SAMPLE = 6,
    CUSTOMER_SAMPLE = 7,
    ADMIN_PRODUCTION = 8,
    CUSTOMER_PRODUCTION = 9,
    SHIPPING = 10,
    COMPLETED = 11,
    ARCHIVE = 12,
}

export enum SKU_ADMIN_STATUS {
    QUOTATION = SKU_ORDER_STATUS.QUOTATION,
    DESIGN = SKU_ORDER_STATUS.DESIGN,
    FABRIC_SOURCING = SKU_ORDER_STATUS.FABRIC_SOURCING,
    TECHNICAL = SKU_ORDER_STATUS.ADMIN_TECHNICAL,
    SAMPLE = SKU_ORDER_STATUS.ADMIN_SAMPLE,
    PRODUCTION = SKU_ORDER_STATUS.ADMIN_PRODUCTION,
    SHIPPING = SKU_ORDER_STATUS.SHIPPING,
    COMPLETED = SKU_ORDER_STATUS.COMPLETED,
    ARCHIVE = SKU_ORDER_STATUS.ARCHIVE,
}

export enum SKU_CUSTOMER_STATUS {
    TECHNICAL = SKU_ORDER_STATUS.CUSTOMER_TECHNICAL,
    SAMPLE = SKU_ORDER_STATUS.CUSTOMER_SAMPLE,
    PRODUCTION = SKU_ORDER_STATUS.CUSTOMER_PRODUCTION,
}
