export const FABRIC_TYPE_MODEL_KEYS = {
    NAME: 'name',
    FABRIC_CODE: 'fabricCode',
    ATTACHMENT: 'attachment',
    ADMIN_NOTES: 'adminNotes',
    SUPPLIER: 'supplier',
    FABRIC_COMPOSITION: 'fabricComposition',
    MOQ: 'moq',
    SUPPLIER_MOQ: 'supplierMoq',
    WIDTH: 'width',
    WEIGHT: 'weight',
    COST: 'cost',
    SUPPLIER_COST: 'supplierCost',
    TAGS: 'tags',
    FLAG: 'flag',
}
